//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShinRyuModManager.Language.UserControls {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LibraryDisplay {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LibraryDisplay() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ShinRyuModManager.Language.UserControls.LibraryDisplay", typeof(LibraryDisplay).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Btn_Install {
            get {
                return ResourceManager.GetString("Btn_Install", resourceCulture);
            }
        }
        
        public static string Btn_Uninstall {
            get {
                return ResourceManager.GetString("Btn_Uninstall", resourceCulture);
            }
        }
        
        public static string Btn_Enable {
            get {
                return ResourceManager.GetString("Btn_Enable", resourceCulture);
            }
        }
        
        public static string Btn_Disable {
            get {
                return ResourceManager.GetString("Btn_Disable", resourceCulture);
            }
        }
        
        public static string Btn_Update {
            get {
                return ResourceManager.GetString("Btn_Update", resourceCulture);
            }
        }
    }
}
