//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShinRyuModManager.Language.Views {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainWindow {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindow() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ShinRyuModManager.Language.Views.MainWindow", typeof(MainWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Btn_Install {
            get {
                return ResourceManager.GetString("Btn_Install", resourceCulture);
            }
        }
        
        public static string Btn_Refresh {
            get {
                return ResourceManager.GetString("Btn_Refresh", resourceCulture);
            }
        }
        
        public static string Btn_Run {
            get {
                return ResourceManager.GetString("Btn_Run", resourceCulture);
            }
        }
        
        public static string Btn_Run_Tooltip {
            get {
                return ResourceManager.GetString("Btn_Run_Tooltip", resourceCulture);
            }
        }
        
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        public static string Menu_Changelog {
            get {
                return ResourceManager.GetString("Menu_Changelog", resourceCulture);
            }
        }
        
        public static string Menu_CheckUpdates {
            get {
                return ResourceManager.GetString("Menu_CheckUpdates", resourceCulture);
            }
        }
        
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        public static string Menu_InstallMod {
            get {
                return ResourceManager.GetString("Menu_InstallMod", resourceCulture);
            }
        }
        
        public static string Menu_Libraries {
            get {
                return ResourceManager.GetString("Menu_Libraries", resourceCulture);
            }
        }
        
        public static string Menu_Manage {
            get {
                return ResourceManager.GetString("Menu_Manage", resourceCulture);
            }
        }
        
        public static string Menu_ModMeta {
            get {
                return ResourceManager.GetString("Menu_ModMeta", resourceCulture);
            }
        }
        
        public static string Menu_ModMetaSampleImage {
            get {
                return ResourceManager.GetString("Menu_ModMetaSampleImage", resourceCulture);
            }
        }
        
        public static string Menu_ModMetaSampleYaml {
            get {
                return ResourceManager.GetString("Menu_ModMetaSampleYaml", resourceCulture);
            }
        }
        
        public static string Menu_UninstallMod {
            get {
                return ResourceManager.GetString("Menu_UninstallMod", resourceCulture);
            }
        }
        
        public static string MetaEditCancel_Tooltip {
            get {
                return ResourceManager.GetString("MetaEditCancel_Tooltip", resourceCulture);
            }
        }
        
        public static string MetaEditEnable_Tooltip {
            get {
                return ResourceManager.GetString("MetaEditEnable_Tooltip", resourceCulture);
            }
        }
        
        public static string MetaEditSave_Tooltip {
            get {
                return ResourceManager.GetString("MetaEditSave_Tooltip", resourceCulture);
            }
        }
        
        public static string ModClose_Tooltip {
            get {
                return ResourceManager.GetString("ModClose_Tooltip", resourceCulture);
            }
        }
        
        public static string ModDown_Tooltip {
            get {
                return ResourceManager.GetString("ModDown_Tooltip", resourceCulture);
            }
        }
        
        public static string ModList_Enabled {
            get {
                return ResourceManager.GetString("ModList_Enabled", resourceCulture);
            }
        }
        
        public static string ModList_ModName {
            get {
                return ResourceManager.GetString("ModList_ModName", resourceCulture);
            }
        }
        
        public static string ModList_Title {
            get {
                return ResourceManager.GetString("ModList_Title", resourceCulture);
            }
        }
        
        public static string ModList_Tooltip {
            get {
                return ResourceManager.GetString("ModList_Tooltip", resourceCulture);
            }
        }
        
        public static string ModSave_Tooltip {
            get {
                return ResourceManager.GetString("ModSave_Tooltip", resourceCulture);
            }
        }
        
        public static string ModToggle_Tooltip {
            get {
                return ResourceManager.GetString("ModToggle_Tooltip", resourceCulture);
            }
        }
        
        public static string ModUp_Tooltip {
            get {
                return ResourceManager.GetString("ModUp_Tooltip", resourceCulture);
            }
        }
        
        public static string Menu_Profiles {
            get {
                return ResourceManager.GetString("Menu_Profiles", resourceCulture);
            }
        }
        
        public static string Menu_Profile1 {
            get {
                return ResourceManager.GetString("Menu_Profile1", resourceCulture);
            }
        }
        
        public static string Menu_Profile2 {
            get {
                return ResourceManager.GetString("Menu_Profile2", resourceCulture);
            }
        }
        
        public static string Menu_Profile3 {
            get {
                return ResourceManager.GetString("Menu_Profile3", resourceCulture);
            }
        }
        
        public static string Menu_Profile4 {
            get {
                return ResourceManager.GetString("Menu_Profile4", resourceCulture);
            }
        }
        
        public static string Menu_Profile5 {
            get {
                return ResourceManager.GetString("Menu_Profile5", resourceCulture);
            }
        }
        
        public static string Menu_Profile6 {
            get {
                return ResourceManager.GetString("Menu_Profile6", resourceCulture);
            }
        }
        
        public static string Menu_Profile7 {
            get {
                return ResourceManager.GetString("Menu_Profile7", resourceCulture);
            }
        }
        
        public static string Menu_Profile8 {
            get {
                return ResourceManager.GetString("Menu_Profile8", resourceCulture);
            }
        }
    }
}
